/* Auto-generated by scripts/gen_imgs.py - do not edit. */
#ifndef SPLASH_240X135_IMG_DSC_H
#define SPLASH_240X135_IMG_DSC_H

#include "lvgl.h"

extern const lv_image_dsc_t splash_240x135_img_dsc;

#endif /* SPLASH_240X135_IMG_DSC_H */
