/* Auto-generated by scripts/gen_imgs.py - do not edit. */
#ifndef SPLASH_480X320_IMG_DSC_H
#define SPLASH_480X320_IMG_DSC_H

#include "lvgl.h"

extern const lv_image_dsc_t splash_480x320_img_dsc;

#endif /* SPLASH_480X320_IMG_DSC_H */
