/* Auto-generated by scripts/gen_imgs.py - do not edit. */
#ifndef SPLASH_IMG_DSC_H
#define SPLASH_IMG_DSC_H

#include "lvgl.h"

extern const lv_image_dsc_t splash_img_dsc;

#endif /* SPLASH_IMG_DSC_H */
