/* config.h for libwally-core on ESP-IDF (Xtensa LX6, little-endian, newlib).
 *
 * This is a hand-maintained equivalent of the file generated by the upstream
 * CMake/autotools configure step (external/libwally-core/_cmake/config.h.in).
 * libwally-core's own sources only reference the subset below, so the
 * remaining checks are omitted.  ccan_config.h is included at the end, as in
 * the generated file.
 */

#ifndef LIBWALLYCORE_CONFIG_H
#define LIBWALLYCORE_CONFIG_H

/* Define to 1 if you have the <byteswap.h> header file. */
/* #undef HAVE_BYTESWAP_H */

/* Define to 1 if you have the `explicit_bzero' function. */
/* #undef HAVE_EXPLICIT_BZERO */

/* Define to 1 if you have the `explicit_memset' function. */
/* #undef HAVE_EXPLICIT_MEMSET */

/* inline asm code can be used */
#define HAVE_INLINE_ASM 1

/* Define to 1 if you have the <mbedtls/sha256.h> header file. */
/* #undef HAVE_MBEDTLS_SHA256_H */

/* Define to 1 if you have the <mbedtls/sha512.h> header file. */
/* #undef HAVE_MBEDTLS_SHA512_H */

/* Define to 1 if you have the `memset_s' function. */
/* #undef HAVE_MEMSET_S */

/* Define if we have mmap */
/* #undef HAVE_MMAP */

/* Define if we have posix_memalign */
/* #undef HAVE_POSIX_MEMALIGN */

/* Define to 1 if you have the <sys/mman.h> header file. */
/* #undef HAVE_SYS_MMAN_H */

/* Define if we have unaligned access.  Xtensa does not guarantee safe
 * unaligned access, so leave this undefined to force aligned paths. */
/* #undef HAVE_UNALIGNED_ACCESS */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "libwallycore"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "libwallycore"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libwallycore 1.5.6"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libwallycore"

/* Define to the home page for this package. */
#define PACKAGE_URL ""

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.5.6"

/* Version number of package */
#define VERSION "1.5.6"

/* Define WORDS_BIGENDIAN to 1 if the processor stores words most-significant
 * byte first.  ESP32 is little-endian, so leave it undefined. */
/* #undef WORDS_BIGENDIAN */

/* -- ccan config (inlined from ccan_config.h) ------------------------- */
#include <stddef.h>

#ifdef WORDS_BIGENDIAN
#define HAVE_BIG_ENDIAN 1
#define HAVE_LITTLE_ENDIAN 0
#else
#define HAVE_BIG_ENDIAN 0
#define HAVE_LITTLE_ENDIAN 1
#endif

#ifdef __GNUC__
#define HAVE_ATTRIBUTE_COLD 1
#define HAVE_ATTRIBUTE_NORETURN 1
#define HAVE_ATTRIBUTE_PRINTF 1
#define HAVE_ATTRIBUTE_CONST 1
#define HAVE_ATTRIBUTE_PURE 1
#define HAVE_ATTRIBUTE_UNUSED 1
#define HAVE_ATTRIBUTE_USED 1
#define HAVE_BUILTIN_CONSTANT_P 1
#define HAVE_WARN_UNUSED_RESULT 1
#endif

#ifdef HAVE_BYTESWAP_H
#define HAVE_BSWAP_64 1
#else
#define HAVE_BYTESWAP_H 0
#define HAVE_BSWAP_64 0
#endif

#if defined(AVOID_UNALIGNED_ACCESS) || (defined(HAVE_UNALIGNED_ACCESS) && defined(__arm__))
/* Disable unaligned access when:
 * 1) Explicitly asked to via AVOID_UNALIGNED_ACCESS (e.g. for ubsan builds)
 * 2) For arm builds where unaligned access is incomplete, in that e.g. byte
 * swap instructions can fault on unaligned addresses where a normal load/store
 * would be fine. Since the compiler can optimise some of our accesses into
 * operations like byte swaps, treat this platform as though it doesn't have
 * unaligned access.
 */
#undef HAVE_UNALIGNED_ACCESS
#define HAVE_UNALIGNED_ACCESS 0
#endif

#if HAVE_UNALIGNED_ACCESS
#define alignment_ok(p, n) 1
#else
#define alignment_ok(p, n) ((size_t)(p) % (n) == 0)
#endif

#ifdef HAVE_MBEDTLS_SHA256_H
#define CCAN_CRYPTO_SHA256_USE_MBEDTLS 1
#endif

#ifdef HAVE_MBEDTLS_SHA512_H
#define CCAN_CRYPTO_SHA512_USE_MBEDTLS 1
#endif

#if !defined(WALLY_EXPORT_ALL) && !defined(_WIN32)
void __attribute__((visibility("hidden"))) wally_clear(void* p, size_t len);
#else
void wally_clear(void* p, size_t len);
#endif

#define CCAN_CLEAR_MEMORY(p, len) wally_clear(p, len)

#endif /* LIBWALLYCORE_CONFIG_H */
