#!/usr/bin/env python3
"""Generate the app's images from the source logo.

Inputs
    main/assets/seedmix.png   (source logo, RGBA)

Outputs (previews + embedded LVGL RGB565 C arrays)
    main/assets/splash.png   480x320: logo centered, "SEED MIX" text below
    main/assets/logo.png     small: logo with "SEED MIX" to its right
    main/assets/splash_img.{c,h}
    main/assets/logo_img.{c,h}

Usage:
    python3 scripts/gen_imgs.py
"""

import os

from PIL import Image, ImageDraw, ImageFont

ASSETS = os.path.join(os.path.dirname(__file__), "..", "main", "assets")
SRC = os.path.join(ASSETS, "seedmix.png")

FONT_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

# Brand greens sampled from the logo.
LIGHT_GREEN = (166, 207, 94)   # "SEED"
DARK_GREEN = (48, 92, 43)      # "MIX"
BLACK = (0, 0, 0)

BYTES_PER_LINE = 16


def load_font(size):
    try:
        return ImageFont.truetype(FONT_BOLD, size)
    except OSError:
        return ImageFont.load_default()


def to_rgb565_bytes(img_rgb):
    """Return (w, h, bytes) with little-endian RGB565 pixel data."""
    w, h = img_rgb.size
    px = img_rgb.load()
    data = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            v = (((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)) & 0xFFFF
            data.append(v & 0xFF)
            data.append((v >> 8) & 0xFF)
    return w, h, data


def write_c_array(img_rgb, out_c, out_h, map_name, dsc_name):
    w, h, data = to_rgb565_bytes(img_rgb)
    stride = w * 2

    lines = []
    lines.append("/* Auto-generated by scripts/gen_imgs.py - do not edit. */")
    lines.append("")
    lines.append('#include "lvgl.h"')
    lines.append("")
    lines.append(f"static const uint8_t {map_name}[] = {{")
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append(f"const lv_image_dsc_t {dsc_name} = {{")
    lines.append("    .header = {")
    lines.append("        .magic = LV_IMAGE_HEADER_MAGIC,")
    lines.append("        .cf = LV_COLOR_FORMAT_RGB565,")
    lines.append(f"        .w = {w},")
    lines.append(f"        .h = {h},")
    lines.append(f"        .stride = {stride},")
    lines.append("    },")
    lines.append(f"    .data_size = sizeof({map_name}),")
    lines.append(f"    .data = {map_name},")
    lines.append("    .reserved = NULL,")
    lines.append("};")
    lines.append("")

    os.makedirs(os.path.dirname(out_c), exist_ok=True)
    with open(out_c, "w") as f:
        f.write("\n".join(lines))

    with open(out_h, "w") as f:
        f.write("/* Auto-generated by scripts/gen_imgs.py - do not edit. */\n")
        f.write(f"#ifndef {dsc_name.upper()}_H\n#define {dsc_name.upper()}_H\n\n")
        f.write('#include "lvgl.h"\n\n')
        f.write(f"extern const lv_image_dsc_t {dsc_name};\n\n")
        f.write(f"#endif /* {dsc_name.upper()}_H */\n")


def draw_brand(draw, cx, cy, parts, font):
    """Draw centered multi-color text; parts is [(text, color), ...]."""
    widths = [draw.textlength(text, font=font) for text, _ in parts]
    total = sum(widths)
    x = cx - total / 2.0
    for (text, color), w in zip(parts, widths):
        draw.text((x, cy), text, font=font, fill=color, anchor="lm")
        x += w


def make_splash(logo_rgba):
    img = Image.new("RGB", (480, 320), BLACK)
    draw = ImageDraw.Draw(img)

    logo_size = 184
    logo = logo_rgba.resize((logo_size, logo_size), Image.LANCZOS)
    logo_top = 34
    img.paste(logo, (240 - logo_size // 2, logo_top), logo)

    font = load_font(52)
    cy = logo_top + logo_size + 34
    draw_brand(draw, 240, cy, [("SEED", LIGHT_GREEN), ("MIX", DARK_GREEN)], font)
    return img


def draw_brand_left(draw, x, cy, parts, font):
    """Draw left-aligned multi-color text; parts is [(text, color), ...]."""
    for text, color in parts:
        w = draw.textlength(text, font=font)
        draw.text((x, cy), text, font=font, fill=color, anchor="lm")
        x += w


def make_logo(logo_rgba):
    icon = 32
    font = load_font(22)
    gap = 6
    pad = 4

    logo = logo_rgba.resize((icon, icon), Image.LANCZOS)
    parts = [("SEED", LIGHT_GREEN), ("MIX", DARK_GREEN)]
    probe = ImageDraw.Draw(Image.new("RGB", (1, 1)))
    text_w = sum(probe.textlength(t, font=font) for t, _ in parts)

    w = pad + icon + gap + int(text_w) + pad
    h = icon + 2 * pad
    img = Image.new("RGB", (w, h), BLACK)
    draw = ImageDraw.Draw(img)

    img.paste(logo, (pad, (h - icon) // 2), logo)
    draw_brand_left(draw, pad + icon + gap, h // 2, parts, font)
    return img


def main():
    logo = Image.open(SRC).convert("RGBA")

    splash = make_splash(logo)
    splash.save(os.path.join(ASSETS, "splash.png"))
    write_c_array(splash, os.path.join(ASSETS, "splash_img.c"),
                  os.path.join(ASSETS, "splash_img.h"), "splash_img_map", "splash_img_dsc")

    small = make_logo(logo)
    small.save(os.path.join(ASSETS, "logo.png"))
    write_c_array(small, os.path.join(ASSETS, "logo_img.c"),
                  os.path.join(ASSETS, "logo_img.h"), "logo_img_map", "logo_img_dsc")

    print(f"splash: {splash.size} -> splash.png / splash_img.c")
    print(f"logo:   {small.size} -> logo.png / logo_img.c")


if __name__ == "__main__":
    main()
